In [7]:
import myQMLlib as myQML

#Code to automatically reload the myQMLfunctions module when it is edited
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [2]:
myQML.generate_dataset_pauli(10,100,myQML.X)

(array([[[0.61656822+2.55160181e-18j, 0.41373059+2.22859776e-01j],
         [0.41373059-2.22859776e-01j, 0.38343178-2.55160181e-18j]],
 
        [[0.80979384+4.53977440e-18j, 0.26315962-2.47039311e-01j],
         [0.26315962+2.47039311e-01j, 0.19020616-4.53977440e-18j]],
 
        [[0.66146333-6.29471427e-19j, 0.45966771+4.35955287e-02j],
         [0.45966771-4.35955287e-02j, 0.33853667+6.29471427e-19j]],
 
        [[0.46388561-3.99370287e-18j, 0.29268604+2.50065594e-02j],
         [0.29268604-2.50065594e-02j, 0.53611439+3.99370287e-18j]],
 
        [[0.69866797-1.94438307e-19j, 0.44047414+3.59592910e-02j],
         [0.44047414-3.59592910e-02j, 0.30133203+1.94438307e-19j]],
 
        [[0.46969692-1.02396184e-18j, 0.28352225-2.50869325e-01j],
         [0.28352225+2.50869325e-01j, 0.53030308+1.02396184e-18j]],
 
        [[0.50947451-2.63673924e-18j, 0.4553932 -1.06454873e-01j],
         [0.4553932 +1.06454873e-01j, 0.49052549+2.63673924e-18j]],
 
        [[0.0901345 +3.79208195e-19j, 0.1

In [3]:
dataset = myQML.QuantumDatasetGenerator(10,100,myQML.X)


In [4]:
print(dataset.N_training, dataset.N_test, dataset.pauli_matrix)

dataset.generate_density_matrices()

print(dataset.rho_training.shape, dataset.rho_test.shape)
print(dataset.rho_training[0])

dataset.compute_expectation_values()

print(dataset.expectation_training.shape, dataset.expectation_test.shape)
print(dataset.expectation_training[0])
print(dataset.expectation_test[0])



10 100 [[0.+0.j 1.+0.j]
 [1.+0.j 0.+0.j]]
Density matrices generated.
(10, 2, 2) (100, 2, 2)
[[0.52308368-4.22252472e-18j 0.39700743-1.15577268e-01j]
 [0.39700743+1.15577268e-01j 0.47691632+4.22252472e-18j]]
Expectation values computed.
(10,) (100,)
(0.7940148511576164+0j)
(0.9763380413656797+0j)


In [ ]:
import numpy as np

#testing function to compute partial trace

#firt of all let's define two matrices and consider their tensor product
#the first matrix is 2x2
A = np.array([[1, 2], [3, 4]])
A = A @ A.conj().T / np.trace(A + A.conj().T)
A = A @ A.conj().T / np.trace(A+ A.conj().T)
print(A)
#the second matrix is 3x3
B = np.array([[5, 6, 7], [8, 9, 10], [11, 12, 13]])
B =B @ B.conj().T / np.trace(B + B.conj().T)
print(B)
#their tensor product is a 6x6 matrix
C = np.kron(A, B)
print("Tensor product of A and B:")
print(C)

A_red = myQML.partial_trace(C,[2,3],0)
print("Partial trace of C over the second subsystem:")
print(A_red)

B_red = myQML.partial_trace(C,[2,3],1)
print("Partial trace of C over the first subsystem:")
print(B_red)



[[0.5 1.1]
 [1.1 2.5]]
[[2.03703704 3.03703704 4.03703704]
 [3.03703704 4.53703704 6.03703704]
 [4.03703704 6.03703704 8.03703704]]
Tensor product of A and B:
[[ 1.01851852  1.51851852  2.01851852  2.24074074  3.34074074  4.44074074]
 [ 1.51851852  2.26851852  3.01851852  3.34074074  4.99074074  6.64074074]
 [ 2.01851852  3.01851852  4.01851852  4.44074074  6.64074074  8.84074074]
 [ 2.24074074  3.34074074  4.44074074  5.09259259  7.59259259 10.09259259]
 [ 3.34074074  4.99074074  6.64074074  7.59259259 11.34259259 15.09259259]
 [ 4.44074074  6.64074074  8.84074074 10.09259259 15.09259259 20.09259259]]
Partial trace of C over the second subsystem:
[[ 20.41666667  44.91666667]
 [ 44.91666667 102.08333333]]
Partial trace of C over the first subsystem:
[[10.59259259 15.79259259 20.99259259]
 [15.79259259 23.59259259 31.39259259]
 [20.99259259 31.39259259 41.79259259]]


In [16]:
print(np.allclose(A_red, A))
print(np.allclose(B_red, B))


False
False
