In [2]:
import myQMLlib as myQML

#Code to automatically reload the myQMLfunctions module when it is edited
%load_ext autoreload
%autoreload 2

In [3]:
myQML.generate_dataset_pauli(10,100,myQML.X)

(array([[[0.40169936-6.66942215e-18j, 0.39943999+2.23688429e-01j],
         [0.39943999-2.23688429e-01j, 0.59830064+6.66942215e-18j]],
 
        [[0.59115228+2.16280286e-18j, 0.29439226+2.13183780e-01j],
         [0.29439226-2.13183780e-01j, 0.40884772-2.16280286e-18j]],
 
        [[0.4865295 +1.33779553e-17j, 0.2386079 +7.73898387e-02j],
         [0.2386079 -7.73898387e-02j, 0.5134705 -1.33779553e-17j]],
 
        [[0.38865997-1.29699168e-18j, 0.39768159-2.49127338e-02j],
         [0.39768159+2.49127338e-02j, 0.61134003+1.29699168e-18j]],
 
        [[0.43405653-2.33907681e-18j, 0.32685751-2.45323081e-01j],
         [0.32685751+2.45323081e-01j, 0.56594347+2.33907681e-18j]],
 
        [[0.60880207+4.22266152e-19j, 0.24118828+2.05351590e-01j],
         [0.24118828-2.05351590e-01j, 0.39119793-4.22266152e-19j]],
 
        [[0.49851796-3.34339971e-18j, 0.08364082-8.31555876e-03j],
         [0.08364082+8.31555876e-03j, 0.50148204+3.34339971e-18j]],
 
        [[0.14997355+1.01265988e-18j, 0.1

In [4]:
dataset = myQML.QuantumDatasetGenerator(10,100,myQML.X)


In [5]:
print(dataset.N_training, dataset.N_test, dataset.pauli_matrix)

dataset.generate_density_matrices()

print(dataset.rho_training.shape, dataset.rho_test.shape)
print(dataset.rho_training[0])

dataset.compute_expectation_values()

print(dataset.expectation_training.shape, dataset.expectation_test.shape)
print(dataset.expectation_training[0])
print(dataset.expectation_test[0])



10 100 [[0.+0.j 1.+0.j]
 [1.+0.j 0.+0.j]]
Density matrices generated.
(10, 2, 2) (100, 2, 2)
[[0.24430552-5.42734068e-19j 0.38465911+2.54089637e-02j]
 [0.38465911-2.54089637e-02j 0.75569448+5.42734068e-19j]]
Expectation values computed.
(10,) (100,)
(0.769318222332731+0j)
(0.692261866766466+0j)


In [12]:
import numpy as np
import qutip as qt

#testing function to compute partial trace

#firt of all let's define two matrices and consider their tensor product
#the first matrix is 2x2
A = np.array([[1, 2], [3, 4]])
A = A + A.conj().T
A = A / np.trace(A)
print(A)
#the second matrix is 3x3
B = np.array([[5, 6, 7], [8, 9, 10], [11, 12, 13]])
B = B + B.conj().T
B= B / np.trace(B)
print(B)
#their tensor product is a 6x6 matrix
C = np.kron(A, B)
print("Tensor product of A and B:")
print(C)

A_red = myQML.partial_trace(C,[2,3],0)
print("Partial trace of C over the second subsystem:")
print(A_red)

B_red = myQML.partial_trace(C,[2,3],1)
print("Partial trace of C over the first subsystem:")
print(B_red)
C_Qutip = qt.Qobj(C, dims=[[2, 3], [2, 3]])
A_red_qutip = qt.ptrace(C_Qutip, 0)
print("Partial trace of C over the second subsystem using qutip:")
print(A_red_qutip)
B_red_qutip = qt.ptrace(C_Qutip, 1)
print("Partial trace of C over the first subsystem using qutip:")
print(B_red_qutip)


[[0.2 0.5]
 [0.5 0.8]]
[[0.18518519 0.25925926 0.33333333]
 [0.25925926 0.33333333 0.40740741]
 [0.33333333 0.40740741 0.48148148]]
Tensor product of A and B:
[[0.03703704 0.05185185 0.06666667 0.09259259 0.12962963 0.16666667]
 [0.05185185 0.06666667 0.08148148 0.12962963 0.16666667 0.2037037 ]
 [0.06666667 0.08148148 0.0962963  0.16666667 0.2037037  0.24074074]
 [0.09259259 0.12962963 0.16666667 0.14814815 0.20740741 0.26666667]
 [0.12962963 0.16666667 0.2037037  0.20740741 0.26666667 0.32592593]
 [0.16666667 0.2037037  0.24074074 0.26666667 0.32592593 0.38518519]]
Partial trace of C over the second subsystem:
[[0.2 0.5]
 [0.5 0.8]]
Partial trace of C over the first subsystem:
[[0.18518519 0.25925926 0.33333333]
 [0.25925926 0.33333333 0.40740741]
 [0.33333333 0.40740741 0.48148148]]
Partial trace of C over the second subsystem using qutip:
Quantum object: dims=[[2], [2]], shape=(2, 2), type='oper', dtype=Dense, isherm=True
Qobj data =
[[0.2 0.5]
 [0.5 0.8]]
Partial trace of C over t

In [7]:
print(np.allclose(A_red, A))
print(np.allclose(B_red, B))


False
False
